coverage:
  precision: 2
  round: down
  range: "95...100"

  status:
    project:
      default: false
      tests:
        target: 100%
        paths: ["tests/"]
      pycln:
        target: 100%
        paths: ["pycln/"]
    patch: yes
    changes: yes

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: no
