repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.5.1
    hooks:
      - id: isort
        files: "\\.(py)$"
        args:
          [
            --line-length=88,
            --multi-line=3,
            --force-grid-wrap=0,
            --trailing-comma,
            --use-parentheses,
          ]

  - repo: https://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
      - id: docformatter
        args: [--in-place]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [--line-length=88]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]

  - repo: https://github.com/prettier/prettier
    rev: 2.1.1
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
