[tool.poetry]
name = "pycln"
version = "0.0.0"
description = "Find and remove all unused import statements from your Python files."
authors = ["Hadi Zaki Alqattan <alqattanhadizaki@gmail.com>"]
repository = "https://github.com/hadialqattan/pycln"
keywords = ["formatter", "linter", "quality-assurance", "tools", "cli"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Utilities"
]
license = "MIT"
readme = "README.md"

[tool.poetry.scripts]
pycln = "pycln.cli:app"

[tool.poetry.dependencies]
python = ">=3.6, <=3.10"
typer = "^0.3.1"
toml = "^0.10.1"
pathspec = "^0.8.0"
dataclasses = {version = "^0.7", python = "3.6"}
libcst = "^0.3.10"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"
semver = "^2.10.2"
pytest-mock = "^3.3.1"
pytest-cov = "^2.10.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
